[package]
name = "oof-common"
version = "0.1.0"
authors = ["Jack O'Sullivan <jackos1998@gmail.com>"]
edition = "2018"

[dependencies]
enum_primitive = "~0.1"
quick-error = "~1.2"
log = "~0.4"
bytes = "~0.4"
bufstream = "~0.1"
